% input (1) ID, (2) neighborID: matrix or array showing its ID and its neighbor's ID
% (3) misorientationStruct: generated by other function
function misorientation = find_misorientation_from_structure(ID, neighborID, misorientationStruct)

[nRow,nColumn]=size(ID);
misorientation = zeros(nRow,nColumn);

for iRow = 1:nRow
    for iColumn=1:nColumn
            index1 = find(ID(iRow,iColumn)==misorientationStruct.g1);
            if ~isempty(index1)
                index2 = find(neighborID(iRow,iColumn) == misorientationStruct.g2{index1});
                if ~isempty(index2)
                    misorientation(iRow,iColumn) = misorientationStruct.misorientation{index1}(index2);
                end
           end
    end
end

display('found misorientation for each point');
display(datestr(now));

end
